name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: cheton/ai-code-reviewer@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          AZURE_OPENAI_API_KEY: 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
          AZURE_OPENAI_API_VERSION: "2024-05-01-preview"
          AZURE_OPENAI_DEPLOYMENT: "gpt-4o"
          AZURE_OPENAI_ENDPOINT: "https://api.openai.com/v1/models"
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
